### ISSUE TITLE
无法切换舞台大小

### ISSUE THREAD

**Issue by ghost** [Clipteam/clipcc-desktop#12]
### Expected Behavior

无法切换舞台大小
### Actual Behavior

无法找到切换舞台大小的控件/按钮
### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

Windows10 —— 212h

**Comment by SimonShiki** [comment]
Duplicate Clipteam/clipcc-gui#80
