### ISSUE TITLE
关于页面无法打开

### ISSUE THREAD

**Issue by sparrowhe** [Clipteam/clipcc-desktop#14]
### Expected Behavior

点击关于时，能正常打开关于页面

### Actual Behavior

![image](https://user-images.githubusercontent.com/26871028/183235622-c2554022-586c-4239-b71c-fb16c1fbfab7.png)

打不开，控制台报错
![image](https://user-images.githubusercontent.com/26871028/183235632-8629e874-25f8-46bf-82f2-9edb52667265.png)

### Steps to Reproduce

点击 关于

### Operating System and Browser

Windows 10 19043.1826

**Comment by sparrowhe** [comment]
![image](https://user-images.githubusercontent.com/26871028/183235688-1460f662-b86a-44ac-be6e-74c4276478ea.png)

**Comment by SimonShiki** [comment]
已修复
