### ISSUE TITLE
Append MPR package to installation instructions under the README

### ISSUE THREAD

**Issue by hiddeninthesand** [Clipteam/clipcc-desktop#9]
ClipCC is currently being [packaged on the MPR](https://mpr.makedeb.org/packages/clipcc-bin) for Ubuntu and Debian, which may be considered useful knowledge by users. Installing it from the MPR is very similar to the method you'd use to install it from the AUR on Arch-based systems, with the most popular helper currently being [Tap.](https://github.com/hwittenborn/tap)

**Comment by EdenQwQ** [comment]
> ClipCC is currently being [packaged on the MPR](https://mpr.makedeb.org/packages/clipcc-bin) for Ubuntu and Debian, which may be considered useful knowledge by users. Installing it from the MPR is very similar to the method you'd use to install it from the AUR on Arch-based systems, with the most popular helper currently being [Tap.](https://github.com/hwittenborn/tap)

This mpr package is not ready yet. I simply committed the `PKGBUILD` for AUR and didn't resolve the dependencies. I currently have no debian-based systems installed. If you'd like to contribute to the MPR package, feel free to create a new package (`clipcc` / `clipcc-beta` etc.) Also please contact me on discord if you'd like to be a co-maintainer for `clipcc-bin`
Discord username: Eden#5653

**Comment by hiddeninthesand** [comment]
Unfortunately I only talk over Matrix and email, but I'd be happy to take a look at it.

**Comment by EdenQwQ** [comment]
> Unfortunately I only talk over Matrix and email, but I'd be happy to take a look at it.

Matrix is ok 🫡
edenqwq:matrix.org
